### ISSUE TITLE
fatal error: gcj/cni.h: No such file or directory

### ISSUE THREAD

**Issue by charlesc-ai** [spl/homebrew-pdftk#13] opened 2017-06-27 09:48 UTC
Please report this to the spl/pdftk tap!

==> make -f Makefile.OSX-10.6
Last 15 lines from /Users/xxxx/Library/Logs/Homebrew/pdftk/01.make:
 #pragma GCC java_exceptions

attachments.cc:33:10: fatal error: gcj/cni.h: No such file or directory
 #include <gcj/cni.h>
          ^~~~~~~~~~~
compilation terminated.
pdftk.cc:33:10: fatal error: gcj/cni.h: No such file or directory
 #include <gcj/cni.h>
          ^~~~~~~~~~~
compilation terminated.
make: *** [passwords.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [report.o] Error 1
make: *** [attachments.o] Error 1
make: *** [pdftk.o] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/spl/homebrew-pdftk/issues

**Comment by spl** [comment] 2017-06-27 10:06
Duplicate of #11.

**Closed as completed by spl** 2017-06-27 10:06 UTC
