### ISSUE TITLE
Problem compiling and installing pdftk

### ISSUE THREAD

**Issue by ezeeyahoo** [spl/homebrew-pdftk#14] opened 2017-10-08 17:29 UTC
```
$ brew install pdftk
==> Installing pdftk from spl/pdftk
==> Cloning https://github.com/spl/pdftk.git
Updating /Users/eshant/Library/Caches/Homebrew/pdftk--git
==> Checking out tag v2.02
==> Downloading https://raw.githubusercontent.com/spl/homebrew-pdftk/master/pat
######################################################################## 100.0%
==> Patching
==> Applying patch.diff
patching file pdftk/Makefile.Base
patching file pdftk/Makefile.OSX-10.6
Warning: Calling Formula#cxxstdlib_check in install is deprecated!
Use Formula.cxxstdlib_check outside install instead.
/usr/local/Homebrew/Library/Taps/spl/homebrew-pdftk/pdftk.rb:21:in `install'
Please report this to the spl/pdftk tap!

==> make -f Makefile.OSX-10.6
Last 15 lines from /Users/eshant/Library/Logs/Homebrew/pdftk/01.make:
          ^~~~~~~~~~~
compilation terminated.
passwords.cc:33:10: fatal error: gcj/cni.h: No such file or directory
 #include <gcj/cni.h>
          ^~~~~~~~~~~
compilation terminated.
attachments.cc:33:10: fatal error: gcj/cni.h: No such file or directory
 #include <gcj/cni.h>
          ^~~~~~~~~~~
compilation terminated.
make: *** [report.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [passwords.o] Error 1
make: *** [pdftk.o] Error 1
make: *** [attachments.o] Error 1
```

**Comment by spl** [comment] 2017-10-17 07:21
Duplicate of #11.

**Closed as completed by spl** 2017-10-17 07:21 UTC
