### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by nachopants** [spl/homebrew-pdftk#15] opened 2017-11-17 22:30 UTC
➜  TEST  brew install pdftk

==> Installing pdftk from spl/pdftk
==> Cloning https://github.com/spl/pdftk.git
Updating /Users/nacho/Library/Caches/Homebrew/pdftk--git
==> Checking out tag v2.02
==> Downloading https://raw.githubusercontent.com/spl/homebrew-pdftk/master/patch.diff
######################################################################## 100.0%
==> Patching
==> Applying patch.diff
patching file pdftk/Makefile.Base
patching file pdftk/Makefile.OSX-10.6
Warning: Calling Formula#cxxstdlib_check in install is deprecated!
Use Formula.cxxstdlib_check outside install instead.
/usr/local/Homebrew/Library/Taps/spl/homebrew-pdftk/pdftk.rb:21:in `install'
Please report this to the spl/pdftk tap!

==> make -f Makefile.OSX-10.6
Last 15 lines from /Users/nacho/Library/Logs/Homebrew/pdftk/01.make:
passwords.cc:33:10: fatal error: gcj/cni.h: No such file or directory
 #include <gcj/cni.h>
          ^~~~~~~~~~~
report.cc:33:10: fatal error: gcj/cni.h: No such file or directory
 #include <gcj/cni.h>
          ^~~~~~~~~~~
compilation terminated.
compilation terminated.
compilation terminated.
compilation terminated.
make: *** [passwords.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [report.o] Error 1
make: *** [attachments.o] Error 1
make: *** [pdftk.o] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/spl/homebrew-pdftk/issues

**Comment by spl** [comment] 2017-11-20 06:11
Duplicate of #11.

**Closed as completed by spl** 2017-11-20 06:11 UTC
